#!/bin/bash

place="1.3.6.1.2.1.17.7.1.4.2.1.4.0"
# shellcheck source=/dev/null
source /etc/snmp/snmp.data
mkdir -p "$TMPDIR"

FILE="${TMPDIR}/out_vlanMembers"
DFILE="${TMPDIR}/dbg_vlanMembers"

date +%X > "$DFILE"
echo $place >> "$DFILE"
# shellcheck source=/dev/null
source "$FILE"

while read -r CMD
do
  case "$CMD" in
    PING)
      echo PONG
      continue
      ;;
    getnext)
      read -r REQ
      oid=$(echo "$REQ" | tr -d .)
      eval ret=\$getnext_"${oid}"
      if test "$ret" = "NONE"
      then
        echo NONE
        continue
      fi
      ;;
    get)
      read -r REQ
      if test "$REQ" = "$place"
      then
        echo NONE
        continue
      else
        ret="$REQ"
      fi
      ;;
    *)
      read -r REQ
      if test "$REQ" = "$place"
      then
        echo NONE
        continue
      else
        ret="$REQ"
      fi
      ;;
  esac

  oid=$(echo "$ret" | tr -d .)
  if eval test "x\$type_${oid}" != "x"
  then
    echo "$ret"
    eval echo "\$type_${oid}"
    eval echo "\$value_${oid}"
  else
    echo NONE
  fi
done
